# 01 - Carga y limpieza de datos

Objetivo: preparar la base oficial de COVID-19 Mexico para el analisis econometrico de las fases 1 a 3.

Decisiones metodologicas:
- Periodo: 2020-2026.
- Muestra principal: casos confirmados con clasificacion COVID 1, 2 o 3.
- Fecha epidemiologica principal: `FECHA_SINTOMAS`.
- Hospitalizacion: `TIPO_PACIENTE = 2`.
- Defuncion: `FECHA_DEF` distinta de `9999-99-99`.

In [1]:
from pathlib import Path
import sys

PROJECT_ROOT = Path.cwd().parent if Path.cwd().name == 'notebooks' else Path.cwd()
sys.path.append(str(PROJECT_ROOT))

DATA_RAW = PROJECT_ROOT / 'data' / 'raw'
DATA_PROCESSED = PROJECT_ROOT / 'data' / 'processed'
TABLES_DIR = PROJECT_ROOT / 'reports' / 'tables'
PROCESSED_PATH = DATA_PROCESSED / 'covid_mexico_confirmados_2020_2026.parquet'

PROJECT_ROOT, DATA_RAW, PROCESSED_PATH

(WindowsPath('D:/MyWorkspace/Notebooks/Proyecto Modelos Econométricos - COVID 19'),
 WindowsPath('D:/MyWorkspace/Notebooks/Proyecto Modelos Econométricos - COVID 19/data/raw'),
 WindowsPath('D:/MyWorkspace/Notebooks/Proyecto Modelos Econométricos - COVID 19/data/processed/covid_mexico_confirmados_2020_2026.parquet'))

In [2]:
from src.data_preprocessing import build_confirmed_dataset, validation_summary

summary = build_confirmed_dataset(DATA_RAW, PROCESSED_PATH, chunksize=500_000)
summary

                     archivo  registros_raw  registros_confirmados
0      COVID19MEXICO2020.csv        3868396                1563135
1      COVID19MEXICO2021.csv        8830345                2526649
2      COVID19MEXICO2022.csv        6451944                3195409
3      COVID19MEXICO2023.csv        1222219                 428212
4      COVID19MEXICO2024.csv         177618                  14131
5  COVID19MEXICO20252026.csv         222379                   7634

In [3]:
TABLES_DIR.mkdir(parents=True, exist_ok=True)
summary.to_csv(TABLES_DIR / 'fase_03_resumen_procesamiento.csv', index=False, encoding='utf-8-sig')
summary

                     archivo  registros_raw  registros_confirmados
0      COVID19MEXICO2020.csv        3868396                1563135
1      COVID19MEXICO2021.csv        8830345                2526649
2      COVID19MEXICO2022.csv        6451944                3195409
3      COVID19MEXICO2023.csv        1222219                 428212
4      COVID19MEXICO2024.csv         177618                  14131
5  COVID19MEXICO20252026.csv         222379                   7634

In [4]:
import pandas as pd

processed = pd.read_parquet(PROCESSED_PATH)
validation_summary(processed)

{'registros': 7735170,
 'codigos_confirmados': [1, 2, 3],
 'defuncion_valores': [0, 1],
 'hospitalizacion_valores': [0, 1],
 'fecha_sintomas_min': Timestamp('2020-02-19 00:00:00'),
 'fecha_sintomas_max': Timestamp('2026-05-28 00:00:00')}

In [5]:
processed.head()

,id_registro,archivo_origen,fecha_actualizacion,fecha_ingreso,fecha_sintomas,fecha_def,anio_sintomas,mes_sintomas,semana_sintomas,dias_sintomas_ingreso,...,epoc_dummy,asma_dummy,inmunosupresion_dummy,hipertension_dummy,otra_com_dummy,cardiovascular_dummy,obesidad_dummy,renal_cronica_dummy,tabaquismo_dummy,uci_dummy
0,z4d6fe,COVID19MEXICO2020.csv,2021-10-31,2020-12-06,2020-11-30,NaT,2020,11,49,6,...,0,0,0,0,0,0,0,0,0,<NA>
1,z3bf80,COVID19MEXICO2020.csv,2021-10-31,2020-07-28,2020-07-20,NaT,2020,7,30,8,...,0,0,0,0,0,0,0,0,0,<NA>
2,z54912,COVID19MEXICO2020.csv,2021-10-31,2020-06-12,2020-06-10,NaT,2020,6,24,2,...,0,0,0,0,0,0,0,0,0,<NA>
3,z552ac,COVID19MEXICO2020.csv,2021-10-31,2020-06-02,2020-05-30,NaT,2020,5,22,3,...,0,0,0,0,0,0,0,0,0,<NA>
4,z59345,COVID19MEXICO2020.csv,2021-10-31,2020-07-01,2020-06-30,NaT,2020,6,27,1,...,0,0,0,0,0,0,0,0,0,<NA>